# Generated by Django 2.2.7 on 2021-04-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_auto_20210429_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
    ]
