# Generated by Django 2.2.7 on 2021-04-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_anuncio_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
    ]
